#include <iostream>
#include <iomanip>
#include <locale>

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

#include "vector"
#include "vector"
using std::vector;

#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

TTree          *fChain;   //!pointer to the analyzed TTree or TChain               
Int_t           fCurrent; //!current Tree number in a TChain                       

void divide2(const char* inputfilename, const char* hnum, const char* hdenom) {


  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.


  TFile *f = new TFile(inputfilename);

  gStyle->SetOptStat(111111);

  TString canvName = "Fig_";
  canvName += "haha";

  //  if( writeExtraText ) canvName += "-prelim";
  //if( iPos%10==0 ) canvName += "-out";                                        
  //else if( iPos%10==1 ) canvName += "-left";                                  
  //else if( iPos%10==2 )  canvName += "-center";                               
  //else if( iPos%10==3 )  canvName += "-right";                                
  int W = 800;
  int H = 600;
  TCanvas* canv = new TCanvas(canvName,canvName,50,50,W,H);
  // references for T, B, L, R                                                  
  float T = 0.08*H;
  float B = 0.12*H;
  float L = 0.12*W;
  float R = 0.04*W;

  canv->SetFillColor(0);
  canv->SetBorderMode(0);
  canv->SetFrameFillStyle(0);
  canv->SetFrameBorderMode(0);
  canv->SetLeftMargin( L/W );
  canv->SetRightMargin( R/W );
  canv->SetTopMargin( T/H );
  canv->SetBottomMargin( B/H );
  canv->SetTickx(0);
  canv->SetTicky(0);





  // get histogram of events before trigger
    TH1F* nhist = static_cast<TH1F*>(f->Get(hnum)->Clone());
    TH1F* dhist = static_cast<TH1F*>(f->Get(hdenom)->Clone());
    TH1F* rhist = static_cast<TH1F*>(f->Get(hnum)->Clone());

    rhist->Divide(dhist);

    rhist->Draw();




  canv->Update();
  canv->RedrawAxis();
  canv->GetFrame()->Draw();


  return;


}
