#include <iostream>
#include <iomanip>
#include <locale>

#include <TROOT.h>
#include <TChain.h>
#include <TFile.h>

#include "vector"
#include "vector"
using std::vector;

#include <TH2.h>
#include <TStyle.h>
#include <TCanvas.h>

TTree          *fChain;   //!pointer to the analyzed TTree or TChain               
Int_t           fCurrent; //!current Tree number in a TChain                       

// Fixed size dimensions of array or collections stored in the TTree if any.       





void dumpH(const char* inputfilename, const char* hname) {
  // "ntuple.root", "histos.root"
  // suggest cuts 1000., 0.2,0.9,0.9,1


  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.


  TFile *f = new TFile(inputfilename);

  // get histogram of events before trigger
  TH1F* ahist = static_cast<TH1F*>(f->Get(hname)->Clone());

  int nbin = ahist->GetNbinsX();
  std::cout<<" this histogram has "<<nbin<<" bins"<<std::endl;
  float asum=0.;
  for(int i=0;i<=nbin;i++) {
    float aa = ahist->GetBinContent(i);
    std::cout<<"bin "<<i<<" contains "<<aa<<std::endl;
    asum=asum+aa;
  }
  std::cout<<"integral is "<<asum<<std::endl;

  f->Close();



}
