void fakerates2() {


  // read the Tree generated by tree1w and fill two histograms
  // note that we use "new" to create the TFile and TTree objects,
  // to keep them alive after leaving this function.




  gStyle->SetOptStat(111111);

  TString canvName = "Fig_";
  canvName += "haha";

  //  if( writeExtraText ) canvName += "-prelim";
  //if( iPos%10==0 ) canvName += "-out";                                        
  //else if( iPos%10==1 ) canvName += "-left";                                  
  //else if( iPos%10==2 )  canvName += "-center";                               
  //else if( iPos%10==3 )  canvName += "-right";                                
  int W = 800;
  int H = 600;
  TCanvas* canv = new TCanvas(canvName,canvName,50,50,W,H);
  // references for T, B, L, R                                                  
  float T = 0.08*H;
  float B = 0.12*H;
  float L = 0.12*W;
  float R = 0.04*W;

  canv->SetFillColor(0);
  canv->SetBorderMode(0);
  canv->SetFrameFillStyle(0);
  canv->SetFrameBorderMode(0);
  canv->SetLeftMargin( L/W );
  canv->SetRightMargin( R/W );
  canv->SetTopMargin( T/H );
  canv->SetBottomMargin( B/H );
  canv->SetTickx(0);
  canv->SetTicky(0);


  int n_ = 2;

  float x1_l = 1.2;
  //  float x1_l = 0.75;                                                                  
  float y1_l = 0.80;

  float dx_l = 0.60;
  float dy_l = 0.1;
  float x0_l = x1_l-dx_l;
  float y0_l = y1_l-dy_l;

  TLegend *lgd = new TLegend(x0_l,y0_l,x1_l, y1_l);
  lgd->SetBorderSize(0); lgd->SetTextSize(0.04); lgd->SetTextFont(62); lgd->SetFillColor(\
											 0);




  
  TFile *f = new TFile("SumHistsQCD.rot");
  // 
    TH1F* nhist = static_cast<TH1F*>(f->Get("hjptfra2")->Clone());
    TH1F* dhist = static_cast<TH1F*>(f->Get("hjptfrb")->Clone());
    TH1F* rhist = static_cast<TH1F*>(f->Get("hjptfra2")->Clone());
    
    //f->Close();
    
    rhist->Divide(dhist);
  
    
  
    rhist->SetMaximum(0.02);
    
    rhist->GetXaxis()->SetTitle("efficiency of alphaMax<0.4 and ipMax> 4 mm versus pT");
    
    rhist->SetDirectory(0);
    rhist->SetLineColor(3);
    rhist->SetLineWidth(3);
    rhist->SetStats(0);
    rhist->Draw("");
    rhist->Draw();
    
    
   TFile *f2 = new TFile("SumHistsWSkim.root");
    TH1F* nhist2 = static_cast<TH1F*>(f2->Get("hjpta")->Clone());
    TH1F* dhist2 = static_cast<TH1F*>(f2->Get("hjptb")->Clone());
    TH1F* rhist2 = static_cast<TH1F*>(f2->Get("hjpta")->Clone());
    //f2->Close();


    rhist2->Divide(dhist2);


    rhist2->SetDirectory(0);
    rhist2->SetLineColor(4);
    rhist2->SetLineWidth(3);
    rhist2->SetStats(0);

    rhist2->Draw("same");

   
   TFile *f3 = new TFile("SumHistsWMCSkim.rot");
    TH1F* nhist3 = static_cast<TH1F*>(f3->Get("hjpta")->Clone());
    TH1F* dhist3 = static_cast<TH1F*>(f3->Get("hjptb")->Clone());
    TH1F* rhist3 = static_cast<TH1F*>(f3->Get("hjpta")->Clone());
    //f2->Close();


    rhist3->Divide(dhist3);


    rhist3->SetDirectory(0);
    rhist3->SetLineColor(5);
    rhist3->SetLineWidth(3);
    rhist3->SetStats(0);

    rhist3->Draw("same");



    lgd->AddEntry(rhist, "QCD MC", "l");
    lgd->AddEntry(rhist2, "W plus jet data", "l");
    lgd->AddEntry(rhist3, "W plus jet MC", "l");

    lgd->Draw();


  canv->Update();
  canv->RedrawAxis();
  canv->GetFrame()->Draw();


  return;


}
